# Site settings
title: "Hwejin Jung"
description: "Hwejin Jung Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Hwejin Jung"
resume_title:                   "Artificial Intelligence Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hwejin23@korea.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+82)-10-5059-5766"
resume_contact_address:         "Korea University, Seoul, South Korea"
resume_header_contact_info:     "(+82)-10-5059-5766 • hwejin23@korea.ac.kr"
display_header_contact_info:    "true"

##resume_header_intro: "<p>-asdfasdfasdf asdfasdfasdf \n sdfasdf asdf </p>"
#resume_header_intro: asdfasdfasdf asdfasdfasdf \n sdfasdf asdf

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_publications:     true
resume_section_interests:       true
resume_section_projects:        true
#resume_section_skills:          true



#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
#resume_section_experience:      true



# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hwejin23"
  resume_linkedin_url:          "https://www.linkedin.com/in/hwejin23"
  resume_website_url:           "http://dmis.korea.ac.kr/"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
#  resume_facebook_url:          "insert Facebook URL here"
#  resume_medium_url:            "https://medium.com/@jglovier"
#  resume_instagram_url:         "insert your Instagram URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
